sudo: required

language: java

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  
after_success:
  - docker push pred2k3/aqi-service

script: 
  - mvn clean package
  
cache:
  timeout: 1000
  directories:
    - $HOME/.m2
